_target_: engine.acoustic.fastspeech2.FastSpeech2
n_mels: ${dsp.config.n_mels}
n_speakers: ${corpus.config.n_speakers}
max_length: 3500
n_phonemes: ${text.config.n_phonemes}
encoder_channel: 256
encoder_hidden_channel: 1024
encoder_n_layers: 4
encoder_n_heads: 2
encoder_kernel_size: 9
encoder_dropout: 0.2
decoder_channel: 256
decoder_hidden_channel: 1024
decoder_n_layers: 6
decoder_n_heads: 2
decoder_kernel_size: 9
decoder_dropout: 0.2
variance_adaptor_hidden_channel: 256
variance_adaptor_kernel_size: 3
variance_adaptor_dropout: 0.5
feature_emb_quantize_bin: 256
pitch_stats: ${corpus.config.feature_stats.pitch}
energy_stats: ${corpus.config.feature_stats.mel_energy}