_target_: metric_board.Evaluator
metrics:
  dnsmos:
    _target_: metric_board.metrics.DNSMOS
    sample_rate: ${dsp.config.sample_rate}
    submetric: p808
  mcd:
    _target_: metric_board.metrics.MCD
    sample_rate: ${dsp.config.sample_rate}
    fft_size: ${dsp.config.fft_size}
    hop_size: ${dsp.config.hop_size}
  pesq:
    _target_: metric_board.metrics.PESQ
    original_sample_rate: ${dsp.config.sample_rate}
    metric_sample_rate: 16000
    mode: wb
  pitch:
    _target_: metric_board.metrics.Pitch
    sample_rate: ${dsp.config.sample_rate}
    hop_size: ${dsp.config.hop_size}
    pitch_extract_method: harvest
    scale: log
    distance: rmse
  spectrogram:
    _target_: metric_board.metrics.Spectrogram
    fft_size: ${dsp.config.fft_size}
    hop_size: ${dsp.config.hop_size}
    distance: mae
  mel_spectrogram:
    _target_: metric_board.metrics.MelSpectrogram
    sample_rate: ${dsp.config.sample_rate}
    fft_size: ${dsp.config.fft_size}
    hop_size: ${dsp.config.hop_size}
    n_mels: ${dsp.config.n_mels}
    distance: mae
  stoi:
    _target_: metric_board.metrics.STOI
    sample_rate: ${dsp.config.sample_rate}
    extended: true
  utmos:
    _target_: metric_board.metrics.UTMOS
    sample_rate: ${dsp.config.sample_rate}
  vuv:
    _target_: metric_board.metrics.VUVErrorRate
    sample_rate: ${dsp.config.sample_rate}
    hop_size: ${dsp.config.hop_size}
    pitch_extract_method: harvest