_target_: interface.model.Discriminators
discriminators:
  mpd:
    _target_: engine.vocoder.hifi_gan.MultiPeriodDiscriminator
    period: [2,3,5,7,11]
  msd:
    _target_: engine.vocoder.hifi_gan.MultiScaleDiscriminator