_target_: interface.model.Discriminators
discriminators:
  mpd:
    _target_: engine.vocoder.hifi_gan.MultiPeriodDiscriminator
    period: [2,3,5,7,11]
  mrd:
    _target_: engine.vocoder.univnet.MultiResolutionDiscriminator
    fft_sizes: [512, 1024, 2048, 4096]
    hop_sizes: [128, 256, 512, 1024]
    window_sizes: [512, 1024, 2048, 4096]