defaults:
  - _self_
  - optimizer: adam_w
  - scheduler: exponential

name: smallspeech

data_module:
  _target_: data.TTSDataModule
  corpus: ${corpus.config}
  dsp_processor: ${dsp.config}
  text_processor: ${text.config}
  features_to_extract: [mel_spectrogram, pitch]
  require_duration: false
  segment_size: ${general.segment_size} 
  trim: forward
  normalize: loudness
  batch_size: ${general.batch_size}
  num_workers: 12
  pin_memory: true
  
lightning_module:
  _target_: engine.e2e.E2EEngine
  model:
    _target_: engine.e2e.smallspeech.SmallSpeech
    n_phonemes: ${text.config.n_phonemes}
    sample_rate: ${dsp.config.sample_rate}
    fft_size: ${dsp.config.fft_size}
    hop_size: ${dsp.config.hop_size}
    n_mels: ${dsp.config.n_mels}
    n_samples: 256
    n_bands: 128
    channels: 128
    h_channels: 256
    kernel_size: 7
    n_layers: 8
    n_groups: 1
    adaptive_norm: true
    act: tangma
  discriminator:
    _target_: interface.model.Discriminators
    discriminators:
      mpd:
        _target_: engine.vocoder.hifi_gan.MultiPeriodDiscriminator
        period: [2,3,5,7,11]
      mrd:
        _target_: engine.vocoder.univnet.MultiResolutionDiscriminator
        fft_sizes: [512, 1024, 2048, 4096]
        hop_sizes: [128, 256, 512, 1024]
        window_sizes: [512, 1024, 2048, 4096]
      f0:
        _target_: engine.e2e.smallspeech.F0Discriminator
        c_channels: ${engine.lightning_module.model.channels}
        kernel_sizes: [3, 5, 7, 7]
        dilations: [1, 2, 2, 4]
        conditional: true
      duration:
        _target_: engine.e2e.smallspeech.DurationDiscriminator
        c_channels: ${engine.lightning_module.model.channels}
        kernel_sizes: [3, 5]
        dilations: [1, 1]
        conditional: true
  loss:
    _target_: engine.e2e.smallspeech.SmallSpeechLoss
    sample_rate: ${dsp.config.sample_rate}
    fft_size: ${dsp.config.fft_size}
    hop_size: ${dsp.config.hop_size}
    n_mels: ${dsp.config.n_mels}
    lambda_mel: 45
    lambda_mu: 10
    lambda_prior: 10
  discriminator_loss:
    _target_: engine.vocoder.hifi_gan.HiFiGANDiscriminatorLoss
  optimizer: ${engine.optimizer}
  scheduler: ${engine.scheduler}
  dsp_processor: ${dsp.config}
  valid_metrics:
    _target_: metric_board.Evaluator
    metrics:
      spectrogram:
        _target_: metric_board.metrics.Spectrogram
        fft_size: ${dsp.config.fft_size}
        hop_size: ${dsp.config.hop_size}
        distance: mae
      mel_spectrogram:
        _target_: metric_board.metrics.MelSpectrogram
        sample_rate: ${dsp.config.sample_rate}
        fft_size: ${dsp.config.fft_size}
        hop_size: ${dsp.config.hop_size}
        n_mels: ${dsp.config.n_mels}
        distance: mae
  test_metrics: ${metrics}
  exp_path: ${general.exp_path}
  controls: null
  n_valid_log_samples: 8
  n_test_save_samples: 20